### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by kikillotest** [hudsonfoo/kerbal-openmct#7]
i'm getting on node server this repeated message :
`Proxying request to:  http://localhost:8085/telemachus/datalink`

on the console of chrome's dev tools, i get this kind of message :
`angular.js:10661
GET http://localhost:8080/proxyUrl?url=http://localhost:8085/telemachus/datalin…eVelocityz&v.terrainHeight=v.terrainHeight&v.verticalSpeed=v.verticalSpeed 500 (Internal Server Error)`

so, openmct shows no data.

telemachus is installed and working.
i've git cloned openmct, npm install and edited main.js
i cloned your repo in example as 'kerbal'

**Comment by hudsonfoo** [comment]
Possibly related to https://github.com/nasa/openmct/pull/1159

**Comment by hudsonfoo** [comment]
Might require a change to Open MCT's proxy basically. We may also need to add our own proxy to this plugin instead of relying on Open MCT since they have requirements that may conflict (or it appears so based on the above referenced pull request).

**Comment by hudsonfoo** [comment]
Whoops, I didn't read all their comments. Looks like it's a URI encoding issue in this plugin. Will see about updating that soon. You are welcome to do a pull request if you're up for it.

**Comment by hudsonfoo** [comment]
@kikillotest that should do it. Let me know if this resolves the issue. It worked on my end.

**Comment by kikillotest** [comment]
indeed it works great now thanks

also, i must confess, i was using telemachus v2.0, from ckan. now that i replaced it with the release version 1.6 alpha from github, it's ok.

btw, if you're interested, the URL works with telemachus v2.0, when i remove the r.resource parts

**Comment by Mendrinos24** [comment]
sorry to revisit this old thread, i'm having the same error and have the tried multiple versions of telemachus, none of which yield any different results. I have the latest version of this repo and still no luck. Any ideas?
